# Generated by Django 5.2.17 on 2026-09-08 17:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_pushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinLockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('first_failure_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_failure_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pin_lockouts', to='chores.person')),
            ],
            options={
                'unique_together': {('person', 'ip_address')},
            },
        ),
    ]
